### ISSUE TITLE
Editing block that used in all pages

### ISSUE THREAD

**Issue by ehsantalkhouncheh** [mariojgt/onix-pro#12]
Hi guys,

I have a quastion about this package: consider this situation that i create a lot of blocks and create 100 pages using that blocks(drag & drop) in grape js editor so if i have for exmple typo in one of those blocks and i used it every where what happen when i edit that block(component) i should go throw whole 100 pages and edit them manually or i have another option that i dont know? I mean i expect when i update a block it update all pages that used that block but i dont know if we have this ability or not. Thanks in advance 

BR,
Ehsan

**Comment by mariojgt** [comment]
what happen is once you update that block you just need to open the pages affected and save unfortunately in order to work i have to save the html page as string but if you have 20 pages you just need to re open those pages and pres save, because it handle the plugin update on the edit page load.
