### ISSUE TITLE
Error to load content

### ISSUE THREAD

**Issue by limatheus** [mariojgt/onix-pro#13]
Hi!
I got this error when I try reach /onixpro on my project
```
cURL error 7: Failed to connect to onixpro.net port 443 after 279 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://onixpro.net/api/onix/news/
```
Seems is offline

**Comment by mariojgt** [comment]
Hi limatheus, Yes that was a service that you could load desing from the onix server but that service has been shutdown unfortunately, i have done a quick fix so i don't ping the server.
