### ISSUE TITLE
Sidebar only shows 'Autoload'

### ISSUE THREAD

**Issue by DevelopmentNightmare** [mariojgt/onix-pro#21]
Hi, 

I followed the  exact steps in your video but only 'Autoload' shows up in the editor. I tried adding some test block but it didn't update at all.. did I miss something?

composer require mariojgt/onix
php artisan v:p --force 
(selected right option)
npm install
npm run watch

put this into an empty .blade ->
```
<x-onix::onix.main cssPath="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
javascriptPath="https://youraplication.js"
imageAssetUrlLoader="{{ route('onix.image.load') }}"
imageAssetUrlSave="{{ route('onix.image.save') }}"
saveUrl="{{ route('onix.save') }}"
loadUrl="{{ route('onix.load') }}"
autoLoadingUrl="{{ route('onix.component.load') }}"
/>
```

I added a screenshot so you can see what I see.

<img width="1665" alt="Schermafbeelding 2021-11-14 om 23 07 26" src="https://user-images.githubusercontent.com/12170468/141700495-e630bff6-7f69-40f5-84af-3298e5c07214.png">

**Comment by DevelopmentNightmare** [comment]
<img width="1677" alt="Schermafbeelding 2021-11-15 om 08 00 59" src="https://user-images.githubusercontent.com/12170468/141736496-a958be8b-8de5-47c5-8c0d-59935b833124.png">
Console.log issues:

'SyntaxError: Invalid regular expression: invalid group specifier name' on onixPreset.js line 203
'SyntaxError: Invalid regular expression: invalid group specifier name' on grapeCodeEditor.js line 28

**Comment by mariojgt** [comment]
Look like you have some missing files when you first install and publish did you tried to go /onix to check if the demo was working?

**Comment by DevelopmentNightmare** [comment]
`/onix` just gives a 404 page.

**Comment by mariojgt** [comment]
Sorry is /onix/grape, if that didn't worked i will check the code to make sure no files are missing you can also check the onix pro is free and by default you can create pages and reusable components and save in the database.

**Comment by DevelopmentNightmare** [comment]
Yes, that did work. However it gives me the exact same result as in the screenshot above.

**Comment by mariojgt** [comment]
I just did a fresh laravel 8 install and i got working i am thinking you may have some missing files are you using firefox or chome and what is you laravel version ?

**Comment by DevelopmentNightmare** [comment]
I am using Safari and I'm on Laravel `8.64.0`. In Microsoft Edge it does seem to work. Is it possible to have Safari support in the future?

**Comment by mariojgt** [comment]
i see , the problem is grape js is a library that i use to integrate with laravel so you can build your pages and save as blade file or in the database, the problem with safari is that is becaming the new internet explorer ever site you have so build need to have some if and else for safari i recoment to check the grape js official documentation.

**Comment by DevelopmentNightmare** [comment]
I see. Thank you for clearing this up.
