### ISSUE TITLE
How to add grapsjs popular plugins like "grapesjs-preset-webpage"

### ISSUE THREAD

**Issue by MilanUnjiya4149** [mariojgt/onix-pro#6]
I want to add [grapesjs-preset-webpage](https://github.com/artf/grapesjs-preset-webpage) plugins with onix.

I did try to find out steps/doc on google but I not found.

Your help will be appreciated.

Thank you in advance.

**Comment by mariojgt** [comment]
Hi there so i am not 100 % when i build onix in kind use those presets to create my own simple version unfortunately the grapesjs documentation is very limited but any new plugins you need to add in the onix you can check the file onixPreset.js inside the folder 
onix/Publish/Resource/js/grape/onixPreset.js i add comment line buy line let me know if that help you in any way.

**Comment by MilanUnjiya4149** [comment]
Thank you for your comment.

It's possible via change in vendor\mariojgt\onix\src\views\components\onix\main.blade.php this file.

Load plugin dependency and add plugin name to the plugin array on grapesjs init method.
