### ISSUE TITLE
Save button shows wrong button text on the alert box.

### ISSUE THREAD

**Issue by MilanUnjiya4149** [mariojgt/onix-pro#7]
Save button shows "Yes, delete it!" button text on the alert box, The button text should be "Yes, save it!"

![Screenshot_1](https://user-images.githubusercontent.com/53517616/121307860-0ed56500-c91e-11eb-9fdb-b23f655e3e8a.png)

**Comment by mariojgt** [comment]
Thanks i will fix that one.

**Comment by MilanUnjiya4149** [comment]
Also same mistakes on the loading alert box.
![Screenshot_2](https://user-images.githubusercontent.com/53517616/121316080-93c47c80-c926-11eb-8f5d-dccc9ace03ae.png)
